### PR TITLE
Cleanup and use GFM for README

### PR DESCRIPTION
**Pull request by therubymug**
- Move to GFM (GitHub Flavored Markdown)
- Fix misc typos

### CODE REVIEW

**Comment by pbozeman** [comment]
Nice :)  We'll review this in our community pull party that we do on Tuesday and Thursday :)

**Comment by pbozeman** [comment]
and fyi, I mean't that we'll do this one on Tuesday.

**Comment by tarcieri** [comment]
I'd strongly recommend pulling this ASAP. There are formatting errors in the current README

**Comment by pbozeman** [comment]
Pulled.  Thanks!

**Pull request closed without merging**
