### PR TITLE
Enable the following common apache modules by default: headers, expires, 

### PR DESCRIPTION
**Pull request by cardmagic**
Enable the following common apache modules by default: headers, expires, rewrite

http://support.cloudfoundry.com/entries/20396861-wordpress-htaccess-mod-rewite-amazon-ec2-problem

### CODE REVIEW

**Comment by pbozeman** [comment]
I'm merging this one in, but we really need to move this over to be under direct source control rather than a zip file.  Let's try to get that in before the next change to this.  

Thanks

**Comment by cardmagic** [comment]
Sounds good, I was modeling this from the Tomcat version which is also in a zip file, might want to unzip both of them.

**Comment by pbozeman** [comment]
yes, we're having that discussion with the java folks inside the team too :)

**Comment by pbozeman** [comment]
pulled.  thanks

**Pull request closed without merging**
