### PR TITLE
Fix Ruby recipe file for latest version of Chef

### PR DESCRIPTION
**Pull request by schinen**
I have install vcap via vcap_dev_setup for setup multi node vcap development environment.
while running install ruby 1.8, The error like following link has occurred.

http://support.cloudfoundry.com/entries/20767116-ruby-1-8-7-p334-missing-in-installation-using-chef

I tried the solution Vlad provided, but Problem was not solved.
I investigate the cause of error, I found that bash resource name conflict is the cause.

In the mean time, I created a workaround patch to fix this problem.

Thanks.

### CODE REVIEW

**Comment by schinen** [comment]
Sorry, some problems were not solved yet.

I updated a workaround patch.

**Comment by pbozeman** [comment]
I think this might be fixed in f458bb00.  Pull the latest merge and let us know if you still have problems.

**Comment by chrischt** [comment]
Is it really working now?

**Comment by schinen** [comment]
@pbozeman :
I tried latest VCAP with default setting (single node/devbox).
devbox was installed successfully, and test app was worked fine.

Thanks.

@chrischt :
Try latest VCAP.

**Pull request closed without merging**
