### PR TITLE
Add the option to require HTTPs for management (for admins or everyone)

### PR DESCRIPTION
**Pull request by admgre**
This adds two optional configuration options to cloud_controller to require HTTPS. One for all users and one for just admins. Both default to false for now.

It also adds a header in the example nginx proxy configuration to forward the protocol being used. There isn't an example of an SSL server entry in the existing simple configuration - but it is pretty easy to surmise what you would change in the SSL entry.

I have a vmc cli change in my repository I can issue a pull request for if this is accepted to tell the user which error caused vmc login to fail (right now if you turn the https requirement on and are already logged in, the error is clear - current vmc login hides it)

(This is a resubmit of pull request #56 from a branch this time _sigh_)

### CODE REVIEW

**Comment by admgre** [comment]
Alright, I haven't gotten the tests up and running yet - but I'll take a stab at it.

**Comment by admgre** [comment]
Alright - this adds a total of 48 examples to the spec tests (12 each for login and info covering the scenarios I could think of).

**Comment by pbozeman** [comment]
I haven't looked into why, but when I apply this pull request, several auth related tests fail when I do a rake spec in the cc directory.  I don't have any failures when I run rake spec on master.  

Can you check that if you pull/merge from master that this pull request runs cleanly from you?

**Comment by admgre** [comment]
yea - I'll set up a quick micro cloud and rerun the tests. My dev instance isn't near "pristine" at the moment which may be the problem

**Comment by admgre** [comment]
All fixed up - I forgot to clean up after myself with the AppConfig changes I made in the tests.

`Finished in 62.9 seconds
198 examples, 0 failures, 16 pending
adam@micro:~/cloudfoundry/vcap/cloud_controller$`

**Comment by pbozeman** [comment]
merged, thanks

**Pull request closed without merging**
