### PR TITLE
Vbox install

### PR DESCRIPTION
**Pull request by matschaffer**
I included a new script that sets up a mini cloud on a Mac with VirtualBox installed. If you think this should be in it's own repo let me know, but since it depends on the install script Trotter set up, I figured I'd include it here.

See http://matschaffer.com/2011/04/cloudfoundry-virtualbox/ for a walkthrough.

Thanks!

### CODE REVIEW

**Comment by matschaffer** [comment]
Note, this is dependent on (and as such includes the commits from) [pull request 21](https://github.com/cloudfoundry/vcap/pull/21)

**Comment by pbozeman** [comment]
We just pulled trotter's stuff over (Thanks Trotter!)  Can you address the s3 comment I made and resubmit this with a fix for that as well having the parent for this be off cf/vcap/master?

Also, in the future, for things like checking 06db160, we'd like people to rebase those together prior to a pull request.  We're going to get some guidance out about this.  Otherwise we end up squashing them over here during the pull.

Thanks

**Comment by pbozeman** [comment]
opps.. didn't mean to close this :)

**Comment by auser** [comment]
I also spent time with a one line `quickstart` if anyone is interested

```
https://github.com/auser/cloudfoundry-quickstart
```

**Comment by pbozeman** [comment]
Just a reminder, we won't be able to pull this while it references a opaque blob in s3.

Thanks

**Comment by matschaffer** [comment]
What's you're preferred solution on that? I'd be happy to have it reference a cloudfountry-owned bucket if you can set one up. Another option would be automating the ubuntu install, but it'd require quite a bit more work.

**Comment by pbozeman** [comment]
If we are going to host something like this in our repo, it should automate the install.  Alternatively, you can have the user just start from the point of a stock ubuntu install and then your script can set things up from there.

**Comment by matschaffer** [comment]
If you have an ubuntu already, trotter's script is probably plenty.
I'll see what I can do about an ubuntu kickstart or otherwise
automated install.

-Mat

On Jun 1, 2011, at 5:33 PM, pbozeman
reply@reply.github.com
wrote:

**Comment by pbozeman** [comment]
We'd love to see this get finalized and merged into the repo.  We're going to close this for the time being.  When there is a version of this request that self-builds, rather than pointing to a tarball in a remote object store, please reopoen this and we'll pull it over.

Thanks

**Comment by matschaffer** [comment]
Understood. I'll reopen this when I figure out how to automate an install
from an ISO.
-Mat

**Pull request closed without merging**
