### PR TITLE
Introducing support for internal SSL communication.

### PR DESCRIPTION
**Pull request by kpymkata**
Secured corporate landscapes may require that communication traffic be encrypted. So we have prepared a change, which makes internal traffic go over SSL, where appropriate. For these purposes:
- suitable SSL certificates must be generated and provided as new configuration properties
- a java keystore file must be provided inside tomcat/conf. We have included a simple and dummy one
- an HTTPS connector in Tomcat must be enabled. The keystore password is "cloudfoundry".
- the nginx servers must be recompiled against the OpenSSL library, and several other nginx modules/plugins.
- we have adopted the strategy of using a nginx server in front of the cloud controller, having opened both plain HTTP and HTTPS servers.

Note: This change is relevant for Tomcat-powered applications only.

Important: Detailed user guide documentation for this change can be found here: https://github.com/cloudfoundry-collaboration/vcap/wiki/Setup-internal-SSL-communicationDear Cloud Foundry contributor,

<p>
If you are reading this message, it means you submitted a pull request in the
Cloud Foundry GitHub repository.
</p>

<p>
First of all, thanks! We really appreciate your participation.
</p>

<p>
Recently we made some changes in how we are verifying and reviewing open source
contributions like yours. In addition, we changed the way we can expose our
internal development in real-time. The changes are exciting, as they allow all
our staff to collaborate seamlessly with you, which increases our mutual
velocity and gives the community a bigger stake in our direction.
</p>

<p>
The Cloud Foundry team uses Gerrit, a code review tool that originated in the
Android Open Source Project. We also use GitHub as an official mirror, though
all pull requests are accepted via Gerrit.
</p>

<p>
Follow these steps to make a contribution to any of our open source
repositories:
</p>

1. Complete our CLA Agreement for
   [individuals](http://www.cloudfoundry.org/individualcontribution.pdf) or
   [corporations](http://www.cloudfoundry.org/corpcontribution.pdf).
2. Sign up for an account on our public Gerrit server at
   http://reviews.cloudfoundry.org/.
3. Create and upload your public SSH key in your Gerrit account profile.
4. Set your name and email:
   
   ```
           git config --global user.name "Firstname Lastname"
           git config --global user.email "your_email@youremail.com"
   ```
5. Install our gerrit-cli gem:
   
   ```
           gem install gerrit-cli
   ```
6. Clone the Cloud Foundry repo:
   _Note: to clone the BOSH repo, or the Documentation repo, replace
   `vcap` with `bosh` or `oss-docs`_
   
   ```
           gerrit clone ssh://reviews.cloudfoundry.org:29418/vcap
           cd vcap
   ```
7. Make your changes, commit, and push to gerrit:
   
   ```
           git commit
           gerrit push
   ```

<p>
Once your commits are approved by our Continuous Integration Bot (CI Bot) as
well as our engineering staff, return to the Gerrit interface and MERGE your
changes. The merge will be replicated to GitHub automatically at
https://github.com/cloudfoundry. If you get feedback on your submission, we
recommend squashing your commit with the original change-id. See the squashing
section here for more details: https://help.github.com/rebase.
</p>

### CODE REVIEW

**Comment by pbozeman** [comment]
I'm going to follow up about this one over email.  We've got a couple of threads going on you guys about various items, and a teleconference of in person chat would provide for higher bw communication to talk through them all.

Thanks

**Comment by kpymkata** [comment]
Hi Patrick,

Great to hear that. Me and my colleagues are actively exploring Cloud Foundry, and will be very glad to have a broad discussion with you about our pull requests, whether they are fine and adequate, or they need some refinings, etc.

Best Regards,
Krum.

**Comment by pbozeman** [comment]
Fyi, to anyone following this one.  Krum and the CF team talked on the phone this morning.

We're likely going to pull it in, but want the pull request to be framework agnostic first.  This likely means doing the app/dea side termination in nginx.  Krum is investigating this as an option.

**Comment by ghost** [comment]
Refactor the internal-ssl proposal so tat it is framework agnostic:
-The DEA now passes 2 ports to the start script these are the public port (-p) taht is used to access the app and the bacend port (-b) that is the proxy pass port in nginx
-A general resources folder is created. It is shard by all frameworks and contains a template for nginx virtual host. Ports are parametrized to be filled by ERB
-Several frameworks have been adapted to use the new setup (nginx in front).

-wiki page at  https://github.com/cloudfoundry-collaboration/vcap/wiki/Setup-internal-SSL-communication has been updated to reflect the changes.

The tests need some updates in order to pass. I will follow with another pull request on Monday. It will fix the tests.

**Comment by ghost** [comment]
Here are the updated tests:
https://github.com/cloudfoundry/vcap-tests/pull/9

**Comment by ramonskie** [comment]
any update on this?
because i was wondering why this isn't pulled yet..

**Comment by soudmaijer** [comment]
Any news on this item? Because it is a much requested feature I think.

**Pull request closed without merging**
