### PR TITLE
Adding support for (optional) configuring of port ranges for the DEA droplets.

### PR DESCRIPTION
**Pull request by kpymkata**
Currently, the DEA nodes use the ephemeral port range from the underlying OS, for picking up a port number to supply to each droplet. This range can be configured, and probably the network stack should be restarted for the change to take effect. 

This pull request provides a new configuration property for DEA nodes: port_range, which allows you to specify some range, in terms of Ruby range literal, that will be considered when choosing the port. DEA will try to pick up a random port within the range, which is free, if possible. If this fails, a fallback variant is applied, which is the default behaviour - using the ephemeral port range. This has the advantage that only the DEA must be restarted in order for the configuration change to take effect.

In a secured corporate setup, the allowed network ports are restricted and tightly controlled. Most administrators would require to be able to specify some port range, rather than having them randomly chosen.

Dear Cloud Foundry contributor,

<p>
If you are reading this message, it means you submitted a pull request in the
Cloud Foundry GitHub repository.
</p>

<p>
First of all, thanks! We really appreciate your participation.
</p>

<p>
Recently we made some changes in how we are verifying and reviewing open source
contributions like yours. In addition, we changed the way we can expose our
internal development in real-time. The changes are exciting, as they allow all
our staff to collaborate seamlessly with you, which increases our mutual
velocity and gives the community a bigger stake in our direction.
</p>

<p>
The Cloud Foundry team uses Gerrit, a code review tool that originated in the
Android Open Source Project. We also use GitHub as an official mirror, though
all pull requests are accepted via Gerrit.
</p>

<p>
Follow these steps to make a contribution to any of our open source
repositories:
</p>

1. Complete our CLA Agreement for
   [individuals](http://www.cloudfoundry.org/individualcontribution.pdf) or
   [corporations](http://www.cloudfoundry.org/corpcontribution.pdf).
2. Sign up for an account on our public Gerrit server at
   http://reviews.cloudfoundry.org/.
3. Create and upload your public SSH key in your Gerrit account profile.
4. Set your name and email:
   
   ```
           git config --global user.name "Firstname Lastname"
           git config --global user.email "your_email@youremail.com"
   ```
5. Install our gerrit-cli gem:
   
   ```
           gem install gerrit-cli
   ```
6. Clone the Cloud Foundry repo:
   _Note: to clone the BOSH repo, or the Documentation repo, replace
   `vcap` with `bosh` or `oss-docs`_
   
   ```
           gerrit clone ssh://reviews.cloudfoundry.org:29418/vcap
           cd vcap
   ```
7. Make your changes, commit, and push to gerrit:
   
   ```
           git commit
           gerrit push
   ```

<p>
Once your commits are approved by our Continuous Integration Bot (CI Bot) as
well as our engineering staff, return to the Gerrit interface and MERGE your
changes. The merge will be replicated to GitHub automatically at
https://github.com/cloudfoundry. If you get feedback on your submission, we
recommend squashing your commit with the original change-id. See the squashing
section here for more details: https://help.github.com/rebase.
</p>

### CODE REVIEW

**Comment by kpymkata** [comment]
This wiki page: https://github.com/cloudfoundry-collaboration/vcap/wiki/Configuring-port-range-on-DEA-nodes is related with the topic.

**Comment by kpymkata** [comment]
Thanks, I think you're right. I've added a commit, which introduces a fast failing in case the port range property is not specified correctly, and a failing of the process in case there is no free port in the port range. Will add a spec test for it as well later.

**Comment by kpymkata** [comment]
We've provided a simple RSpec test for the case of a singleton port range. Maybe the best would be to add it in a new dedicated 'when there is a range of a singleton port' section under 'when running'.

The poor thing here is that the general DEA configuration is modified, within the before :each block. I just couldn't find a way to dynamically change the DEA node, from within a DeaComponent object - it executes the DEA starting command, and does not have a reference to the DEA Ruby object.

Maybe we can avoid this polluting, by moving the port range test under the /unit group, where we directly manipulate the DEA Ruby object ? What do you think ?

**Comment by kpymkata** [comment]
Guys, any news on this change ?

**Comment by pbozeman** [comment]
I missed the specs being added to this.  I'll look at pulling this next.  thanks

**Comment by pbozeman** [comment]
I started the merge on this and did a bunch of testing on it, and found an issue.  See the comment on commit ce5cc9d.

Note that as part of this, I prepped the dea for handling the different methods of grabbing ports, as well has better error handing than the "exit" that is done in this pull request.  That code will make it over to the public vcap repo sometime next week, and you can drop your new changes into that.  (Specifically, there will be a Dea#grab_port that checks for the port_range var and does the right version of port allocation.  That method is then used to grab both the app port and potentially the debug_port.)

**Comment by kpymkata** [comment]
Hi Patrick,

Thanks for your comments and for the issues found! Yes, I think you are right about the race condition here. I wonder then how the generic grab_ephemeral_port method is protected against the same possible dangers, since more or less it looks pretty similar, but probably this is taken care of on a lower OS level, i.e. the networking stack is somehow making a synchronization or other approach to guarantee that a reserved port could not be returned to more than one client. Now we have to do the same thing on the upper Ruby layer.

Weird that we have overlooked this serious problem, definitely this needs some refactoring. I will take care.
Thanks!

**Pull request closed without merging**
