### PR TITLE
Dev setup uaa changes

### PR DESCRIPTION
**Pull request by lukebakken**
- Change to cloud controller configuration to disallow `uaa`, `login` and other non-valid application names by default.
- Change to `uaa` setup template to configure it with the right values.

### CODE REVIEW

**Comment by dsyer** [comment]
Thanks for the patch
- The uris that are registered for the UAA do need to be changed, but we need at least uaa.vcap.me to be on the list.
- The domain name in the redirect URI is actually intentional (it might even break something if you fix it).
- I'm not sure why "foo" and "bar" need to be excluded from the list of valid app names

I modified your patch and pushed it to my fork if you want to take a look. and see if you agree.

**Comment by lukebakken** [comment]
foo and bar were in the commented out list, I figured I'd leave them there in the uncommented one.

I found that if you're using a custom domain and don't set both the `uaa` and `login` domain in the `uaa.uris` setting and also fix `redirect-uri`, then you can't log in using `vmc` and `uaa`.

**Comment by dsyer** [comment]
I'd like to see more detail on the custom domain problem.  I really don't see any need to register login.<mydomain> and it prevents you from deploying a _real_ login server.  The redirect uris similarly should be independent of any authentication protocol, but there might be a problem with vmc (in which case lets take it to the vmc repo).

**Comment by mkocher** [comment]
Since this is on @dsyer's fork, can we go ahead and close this?

**Comment by lukebakken** [comment]
@mkocher sounds good to me go right ahead.

**Pull request closed without merging**
