### PR TITLE
Small improvement to specify supported runtimes and frameworks in App model (DRY)

### PR DESCRIPTION
**Pull request by wallyqs**
Currently the supported runtimes and frameworks already specified in `cloud_controller/config/cloud_controller.yml` and `staging/lib/vcap/manifests/*` respectively, are hard coded in the App model at ~cloud_controller/app/models/app.rb~.

With this patch, this duplication will be avoided, making easier to specify which runtimes and frameworks are supported without having to modify the App model directly.Dear Cloud Foundry contributor,

<p>
If you are reading this message, it means you submitted a pull request in the
Cloud Foundry GitHub repository.
</p>

<p>
First of all, thanks! We really appreciate your participation.
</p>

<p>
Recently we made some changes in how we are verifying and reviewing open source
contributions like yours. In addition, we changed the way we can expose our
internal development in real-time. The changes are exciting, as they allow all
our staff to collaborate seamlessly with you, which increases our mutual
velocity and gives the community a bigger stake in our direction.
</p>

<p>
The Cloud Foundry team uses Gerrit, a code review tool that originated in the
Android Open Source Project. We also use GitHub as an official mirror, though
all pull requests are accepted via Gerrit.
</p>

<p>
Follow these steps to make a contribution to any of our open source
repositories:
</p>

1. Complete our CLA Agreement for
   [individuals](http://www.cloudfoundry.org/individualcontribution.pdf) or
   [corporations](http://www.cloudfoundry.org/corpcontribution.pdf).
2. Sign up for an account on our public Gerrit server at
   http://reviews.cloudfoundry.org/.
3. Create and upload your public SSH key in your Gerrit account profile.
4. Set your name and email:
   
   ```
           git config --global user.name "Firstname Lastname"
           git config --global user.email "your_email@youremail.com"
   ```
5. Install our gerrit-cli gem:
   
   ```
           gem install gerrit-cli
   ```
6. Clone the Cloud Foundry repo:
   _Note: to clone the BOSH repo, or the Documentation repo, replace
   `vcap` with `bosh` or `oss-docs`_
   
   ```
           gerrit clone ssh://reviews.cloudfoundry.org:29418/vcap
           cd vcap
   ```
7. Make your changes, commit, and push to gerrit:
   
   ```
           git commit
           gerrit push
   ```

<p>
Once your commits are approved by our Continuous Integration Bot (CI Bot) as
well as our engineering staff, return to the Gerrit interface and MERGE your
changes. The merge will be replicated to GitHub automatically at
https://github.com/cloudfoundry. If you get feedback on your submission, we
recommend squashing your commit with the original change-id. See the squashing
section here for more details: https://help.github.com/rebase.
</p>

### CODE REVIEW

**Comment by leto** [comment]
I like it. There will be a private -> public merge very soon. After that, I will try to get this merged.

**Comment by wallyqs** [comment]
Thank you, I hope this helps :)

**Comment by pbozeman** [comment]
'bundle exec rake spec' in the health_manager directory fails after pulling this.  The health_manager imports the cloud_controller models and these now require the hm to have the frameworks portion of the config.  The hm tests aren't setting this up.  I believe you only need to add this to @hm_cfg in health_manager_spec.rb, but I haven't checked.  

One of us can do this, but it would be great if you could resubmit this with a working hm spec.

Thanks

**Comment by wallyqs** [comment]
Hello Patrick, thank you very much for the review.

I apologize for I did not notice this change in behavior in the Health Manager.

I took a better look at Health Manager this time and I figured out that in order to make these modifications work for the Health Manager as well, it is needed to require the staging initializer from the Cloud Controller before loading its App model. With this change, the Health Manager tests now run without trouble, so I think that no change to the tests should be necessary.

Regards

**Comment by leto** [comment]
@pbozeman do we want to pull in this additional commit, or are we happy with the way we resolved this yesterday?

**Pull request closed without merging**
