### PR TITLE
Remove mysql_fiber_patch vendored plugin

### PR DESCRIPTION
**Pull request by krobertson**
This plugin is no longer necessary with Rails.  It is to call a `remove_stale_cached_threads!` method on the ConnectionPool when it is trying to clear stale connections, however that method was removed from Rails prior to the 3.0.0 official release:

https://github.com/rails/rails/commit/42be67e8d4470b0bdc6ba62fceaa6cdb1c21a097

Currently, the cloud controller will start up and work for a while with this plugin present, however when it needs to clear stale connections, it will error out with a `NoMethodError` and be essentially stuck, since it needs to clear connections but fails every time.

Since commits are obscured prior to April 11th, my guess is this was added to an earlier version that was based on a Rails 3.0 rc/beta and development now primarily happens on pg.Dear Cloud Foundry contributor,

<p>
If you are reading this message, it means you submitted a pull request in the
Cloud Foundry GitHub repository.
</p>

<p>
First of all, thanks! We really appreciate your participation.
</p>

<p>
Recently we made some changes in how we are verifying and reviewing open source
contributions like yours. In addition, we changed the way we can expose our
internal development in real-time. The changes are exciting, as they allow all
our staff to collaborate seamlessly with you, which increases our mutual
velocity and gives the community a bigger stake in our direction.
</p>

<p>
The Cloud Foundry team uses Gerrit, a code review tool that originated in the
Android Open Source Project. We also use GitHub as an official mirror, though
all pull requests are accepted via Gerrit.
</p>

<p>
Follow these steps to make a contribution to any of our open source
repositories:
</p>

1. Complete our CLA Agreement for
   [individuals](http://www.cloudfoundry.org/individualcontribution.pdf) or
   [corporations](http://www.cloudfoundry.org/corpcontribution.pdf).
2. Sign up for an account on our public Gerrit server at
   http://reviews.cloudfoundry.org/.
3. Create and upload your public SSH key in your Gerrit account profile.
4. Set your name and email:
   
   ```
           git config --global user.name "Firstname Lastname"
           git config --global user.email "your_email@youremail.com"
   ```
5. Install our gerrit-cli gem:
   
   ```
           gem install gerrit-cli
   ```
6. Clone the Cloud Foundry repo:
   _Note: to clone the BOSH repo, or the Documentation repo, replace
   `vcap` with `bosh` or `oss-docs`_
   
   ```
           gerrit clone ssh://reviews.cloudfoundry.org:29418/vcap
           cd vcap
   ```
7. Make your changes, commit, and push to gerrit:
   
   ```
           git commit
           gerrit push
   ```

<p>
Once your commits are approved by our Continuous Integration Bot (CI Bot) as
well as our engineering staff, return to the Gerrit interface and MERGE your
changes. The merge will be replicated to GitHub automatically at
https://github.com/cloudfoundry. If you get feedback on your submission, we
recommend squashing your commit with the original change-id. See the squashing
section here for more details: https://help.github.com/rebase.
</p>

### CODE REVIEW

**Comment by d** [comment]
"run for a while" caught my eyes. is there some way to repro this fast?

**Comment by krobertson** [comment]
I will see if I can do a quick repo on a test box.  I think the quickest way would be to set a small connection pool and quickly make several requests.  I'll follow up with actual repo steps.

**Comment by paloaltocp** [comment]
Even though I've deleted these these two files, cloud_controller crashes every once in a while due to an "Eventmachine error, dead fiber called". How should I properly remove these two files from the Cloud Foundry?

**Comment by krobertson** [comment]
Then you ran into the second issue I had, but hadn't confirmed it was from my own customizations or not.  It is definitely an issue with eventmachine/mysql2, but wasn't sure if the stock cloud controller hit it.

Issue covered here:  https://github.com/brianmario/mysql2/issues/188

Patch here: https://gist.github.com/1058768

The fiber support for mysql2 was being moved to em-sychrony, but em-synchrony requires eventmachine 1.0 and cloudfoundry is locked on an older patched version of eventmachine.

I basically turned the patch into another vendored plugin and it fixed it.

And I haven't forgotten about repo steps for this request, and work on a pull request for the issue engindog mentioned.

**Comment by krobertson** [comment]
I had tried to do some simple steps to reproduce it, but couldn't.  I still think it is an issue, because from the Rails commit, the method is clearly removed before 3.0.0 officially came out, however couldn't see simple reproduction steps.

Perhaps review it and consider it, or wait until more people report it after trying to use the cloud controller on mysql.

**Pull request closed without merging**
