### PR TITLE
Erlang support

### PR DESCRIPTION
**Pull request by paulj**
Support for deploying Erlang/OTP applications that have been packaged via Rebar.

### CODE REVIEW

**Comment by paulj** [comment]
I've refactored the support quite a bit now to be based on Erlang/OTP (using rebar) instead of just pure Erlang (which was probably making too many assumptions). I've also added a docs/erlang-otp.md describing how to deploy a non-trivial Erlang application (Sean Cribb's riak_id - https://github.com/seancribbs/riak_id).

Feedback on whether the revised approach seems feasible would be much appreciated.

**Comment by tarcieri** [comment]
Looks good to me... I might try pulling your changes and testing it out

**Comment by pbozeman** [comment]
We'll get reviewed and pulled shortly, pending any feedback.  That being said, before we can pull it, we want to add the ability to enable/disable frameworks so that we don't disrupt the large production system at Cloud Foundry until this has been through our load/stress tests.  We'll enable it in the Microcloud context out of the gate though.

Thanks!

**Comment by pbozeman** [comment]
pulled.  Thanks!

**Comment by ciberch** [comment]
@paulj thanks for this contribution I got mochiwebtest up and running on my vcap instance !

**Pull request closed without merging**
