### PR TITLE
Adding the Neo4j graph database as service provider to CloudFoundry

### PR DESCRIPTION
**Pull request by jexp**
We provided support for installing (vcap_setup) Neo4j server and hosting extension into /var/vcap/service/neo4j

We added the necessary scripts for starting the nodes and provisioning gateway.

Also provided the scripts that allow provisioning/unprovisioning by creating a separate server instance per service provisioning request, creating admin credentials.

For binding requests another set of credentials is created and a read-write or read-only user is added to the running server using its admin API (contained in neo4j-hosting-extension)

### CODE REVIEW

**Comment by pbozeman** [comment]
This is awesome.  We'll review this and either pull it or respond with feedback a bit later this week.

Thanks!

**Comment by pbozeman** [comment]
I originally thought this had a vcap-tests based test for it too.  Can you submit a test app to that repo and a cucumber feature that makes sure the service can bind correctly to apps?

Thanks

**Comment by jexp** [comment]
Patrick, 

sure, working on that, but got distracted and also wanted to update to the latest version of Neo4j :)

Michael

Am 17.05.2011 um 23:19 schrieb pbozeman:

**Comment by pbozeman** [comment]
pulled.  thanks

**Pull request closed without merging**
